# -*- coding: utf-8 -*-
"""File-handling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jgZYX-r5GNbvgOe2TvsZ_PG7fPO5Bj59
"""

import os

"""# Creating files"""

path = 'File-path'
fileName = 'Simple-text-file.txt'
buff = "ABCD \n"
with open(os.path.join(path,fileName), 'w') as temp_file: ##### creating the file
    temp_file.write(buff)

"""# Rename the file name"""

new_fileName = 'new-text-file.txt'
os.rename(os.path.join(path,fileName), os.path.join(path,new_fileName))

"""#Creating new directory"""

new_dir_name = 'New-folder'

os.mkdir(os.path.join(path,new_dir_name))

"""# Deleting new directory"""

os.rmdir(os.path.join(path,new_dir_name))

"""#Editing Text file"""

buff = "Hello world \nThis is CS371. \n"

with open(os.path.join(path,fileName), 'w') as temp_file: ##### creating the file
    temp_file.write(buff)
with open(os.path.join(path,fileName), 'r') as temp_file: 
    list_contents = temp_file.readlines() ### get a list containing each line in the opened file

list_contents[1] = 'This is CS371 Edited'

with open(os.path.join(path,fileName), 'w') as temp_file: ##### openning the file again and write the edited line
   temp_file.writelines(list_contents)

"""# List of the contents in a directory"""

files = os.listdir(path)

for file in files:
  print(file)

